/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.lang.reflect.Array;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void jsonFileObjectTest(){
        ArrayList<Quotes> quotes= new ArrayList<>();
        try {
            FileReader jsonFile = new FileReader("/home/nawal/401/quotes/app/src/main/resources/recentquotes.json");
            quotes = App.readJsonFile(jsonFile);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        assertEquals("Charles Dickens",quotes.get(1).getAuthor());
        assertEquals("18651 likes",quotes.get(0).getLikes());

    }
    @Test void jsonAPITest(){

    }
}
