/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;


public class App {
    public static void main(String[] args) {
        try {
            FileReader quotesFile = new FileReader("app/src/main/resources/recentquotes.json");
            ArrayList<Quotes> quotes= readJsonFile(quotesFile);
            int rand = (int) (Math.random() * (quotes.size()));
            System.out.println("---------------------------------------------------Quote---------------------------------------------------");
            System.out.println(quotes.get(rand).toString());
            System.out.println("---------------------------------------------------Quote---------------------------------------------------");

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

    public static ArrayList<Quotes> readJsonFile(FileReader jsonFile) {
        // create Gson instance
        Gson gson = new Gson();

        // create a reader
        BufferedReader reader = new BufferedReader(jsonFile);

        // convert JSON array to list of users
        ArrayList<Quotes> quotes = gson.fromJson(reader,new TypeToken<ArrayList<Quotes>>() {}.getType());

        try {
            // close reader
            reader.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
        return quotes;
    }
}
